import org.springframework.core.annotation.AbstractAliasAwareAnnotationAttributeExtractor;
public class FunctionUse679 {
public void funcUse() {
AbstractAliasAwareAnnotationAttributeExtractor abstractaliasawareannotationattributeextractor = new AbstractAliasAwareAnnotationAttributeExtractor();
abstractaliasawareannotationattributeextractor.getRawAttributeValue(null);
}
}