import org.springframework.core.annotation.AbstractAliasAwareAnnotationAttributeExtractor;
public class FunctionUse683 {
public void funcUse() {
AbstractAliasAwareAnnotationAttributeExtractor abstractaliasawareannotationattributeextractor = new AbstractAliasAwareAnnotationAttributeExtractor();
abstractaliasawareannotationattributeextractor.getAnnotatedElement();
}
}